name: TEAenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.23.5
      - pandas==2.2.3
      - prodec==1.0.2
      - tqdm==4.67.1
      - matplotlib==3.10.1